import { Toaster } from '@ocmi/frontend/ui/components/sonner';
import { AuthProvider } from '../contexts/Auth.context';
import './global.css';

export const metadata = {
  title: 'Welcome to apps/frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      className="bg-ligth dark:bg-dark text-dark dark:text-ligth"
    >
      <body className="min-h-screen">
        <AuthProvider>{children}</AuthProvider>
        {/* ADD SONNER TOASTER COMPONENT HERE TO DISPLAY TOASTS IN THE APP  */}
        <Toaster richColors />
      </body>
    </html>
  );
}
